import { getStatusBarHeight } from 'react-native-iphone-x-helper';
import { Dimensions, Platform, PixelRatio } from 'react-native';
import ExtraDimensions from 'react-native-extra-dimensions-android';
import strings from './Strings';

//Default
export const WIDTH_DEVICE = Dimensions.get('window').width;
export const HEIGHT_DEVICE =
  Platform.OS === 'ios'
    ? Dimensions.get('window').height
    : ExtraDimensions.get('REAL_WINDOW_HEIGHT');
export const IS_IOS = Platform.OS === 'ios';
export const IS_ANDROID = Platform.OS === 'android';
const defaultWidth = WIDTH_DEVICE / 375;
const defaultHeight = HEIGHT_DEVICE / 667;
//Scale ratio
export const SCALE_WIDTH = (scaleWidth = 100) =>
  Math.round(PixelRatio.roundToNearestPixel(scaleWidth * defaultWidth));
export const SCALE_HEIGHT = (scaleHeight = 177.87) =>
  Math.round(PixelRatio.roundToNearestPixel(scaleHeight * defaultHeight));

export const SCALE_WIDTH_PERCEN = (scaleWidthPercen = 100) => {
  const elemWidth = parseFloat(scaleWidthPercen);
  return PixelRatio.roundToNearestPixel((WIDTH_DEVICE * elemWidth) / 100);
};
export const SCALE_HEIGHT_PERCEN = (scaleHeightPercen = 100) => {
  const elemHeight = parseFloat(scaleHeightPercen);
  return PixelRatio.roundToNearestPixel((HEIGHT_DEVICE * elemHeight) / 100);
};
//font scale Use iPhone6 as base size which is 375 x 667
export const FONTSIZE = (size = 14) => {
  const fontSize = size * defaultWidth;
  if (Platform.OS === 'ios') {
    return Math.round(PixelRatio.roundToNearestPixel(fontSize));
  }
  return Math.round(PixelRatio.roundToNearestPixel(fontSize)) - 2;
};

export const HEADER_HEIGHT = SCALE_HEIGHT(40) + getStatusBarHeight();

console.log('TCL: WIDTH_DEVICE', WIDTH_DEVICE);

console.log('TCL: HEIGHT_DEVICE', HEIGHT_DEVICE);

console.log('TCL: SCALE_WIDTH', SCALE_WIDTH());

console.log('TCL: SCALE_HEIGHT', SCALE_HEIGHT());

console.log('TCL: SCALE_WIDTH_PERCEN', SCALE_WIDTH_PERCEN());

console.log('TCL: SCALE_HEIGHT_PERCEN', SCALE_HEIGHT_PERCEN());

console.log('TCL: FONTSIZE', FONTSIZE());

// export const IMAGE_RESIZE_QUALITY = 100;
// export const IMAGE_RESIZE_MAXWIDTH = 888;
// export const IMAGE_RESIZE_MAXHIEGHT = 500;
// export const IS_IPHONE_X =
//   Platform.OS === 'ios' && Dimensions.get('window').height === 812;
export const ROUTE_KEY = {
  EXCHANGE_TAB: 'EXCHANGE_TAB',
  STORE: 'STORE',
  TERMSCONDITIONSWEBVIEW: 'TERMSCONDITIONSWEBVIEW',
  TERMSCONDITIONS: 'TERMSCONDITIONS',
  BLOCKFRIENDS: 'BLOCKFRIENDS',
  INTEREST: 'INTEREST',
  FAVORATE: 'FAVORATE',
  ADDPROFILE: 'ADDPROFILE',
  SIGNIN: 'SIGNIN',
  SMSVERIFY: 'SMSVERIFY',
  EMAILSIGNUP: 'EMAILSIGNUP',
  PRELOGIN: 'PRELOGIN',
  SPLASH: 'SPLASH',
  MAIN: 'MAIN',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  DRAGGABLEBUTTON: 'DRAGGABLEBUTTON',
  FORGOT_PASS: 'FORGOT_PASS',
  CHOOSE_CATEGORY: 'CHOOSE_CATEGORY',
  FAVOURITE: 'FAVOURITE',
  CHOOSE_ROLE_POST: 'CHOOSE_ROLE_POST',
  CHOOSE_IMAGE_POST: 'CHOOSE_IMAGE_POST',
  CHOOSE_AREA_POST: 'CHOOSE_AREA_POST',
  SUCCESS_POST: 'SUCCESS_POST',
  PREVIEW_BEFORE_POST: 'PREVIEW_BEFORE_POST',
  OTHER_PRODUCT_DETAIL: 'OTHER_PRODUCT_DETAIL',
  MY_PRODUCT_DETAIL: 'MY_PRODUCT_DETAIL',
  LIST_NOTIFICATION: 'LIST_NOTIFICATION',
  LIST_MESSAGE: 'LIST_MESSAGE',
  DETAIL_MESSAGE: 'DETAIL_MESSAGE',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT: 'PAYMENT',
  UPGRADE_PREMIUM: 'UPGRADE_PREMIUM',
  ADD_DIARY: 'ADD_DIARY',
  PRODUCT_FOR_DIARY: 'PRODUCT_FOR_DIARY',
  FRIEND_FOR_DIARY: 'FRIEND_FOR_DIARY',
  FUNCTIONS_OTHER: 'FUNCTIONS_OTHER',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  PRIVATE_PERMISSION: 'PRIVATE_PERMISSION',
  EDIT_PROFILE: 'EDIT_PROFILE',
  EDIT_STORE: 'EDIT_STORE',
  MY_WALLET: 'MY_WALLET',
  HISTORY_TRANSACTION: 'HISTORY_TRANSACTION',
  HISTORY_WITHDRAW: 'HISTORY_WITHDRAW',
  MY_TRANSACTION: 'MY_TRANSACTION',
  DETAIL_TRANSACTION: 'DETAIL_TRANSACTION',
  OTHER_PROFILE_COMPONENT: 'OTHER_PROFILE_COMPONENT',
  POPUP_MENU_AREA_FILTER: 'POPUP_MENU_AREA_FILTER',
  POPUP_MENU_CATEGORY_FILTER: 'POPUP_MENU_CATEGORY_FILTER',
  POPUP_MENU_ORDER_FILTER: 'POPUP_MENU_ORDER_FILTER',
  PAYMENT_RULE: 'PAYMENT_RULE',
  FRIEND: 'FRIEND',
  CREATE_GROUP: 'CREATE_GROUP',
  FIND_GROUP: 'FIND_GROUP',
  TRANSACTION_DETAIL: 'TRANSACTION_DETAIL',
  WITHDRAW_MONEY: 'WITHDRAW_MONEY',
  PAYMENT_WEBVIEW: 'PAYMENT_WEBVIEW',
  ROAD_MAP: 'ROAD_MAP',
  DETAIL_GROUP: 'DETAIL_GROUP',
  EDIT_GROUP: 'EDIT_GROUP',
  GROUP_MEMBERS: 'GROUP_MEMBERS',
  GROUP_STORE_MEMBERS: 'GROUP_STORE_MEMBERS',
  POST_DETAIL: 'POST_DETAIL',
  CREDIT_CARD_INPUT: 'CREDIT_CARD_INPUT',
  POPUP_ATTRIBUTES_FILTER: 'POPUP_ATTRIBUTES_FILTER',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  PREVIEW_BEFORE_POST_MAP_COMPONENT: 'PREVIEW_BEFORE_POST_MAP_COMPONENT',
  WEB_RTC: 'WEB_RTC',
  INCOMING_CALL_NOTIFICATION: 'INCOMING_CALL_NOTIFICATION',
  DETAIL_ORGANIZATION_COMPONENT: 'DETAIL_ORGANIZATION_COMPONENT',
  PRESIDENT_DASHBOARD_COMPONENT: 'PRESIDENT_DASHBOARD_COMPONENT',
  PARTNER_DETAIL_COMPONENT: 'PARTNER_DETAIL_COMPONENT',
  CREATE_POST_COMPONENT: 'CREATE_POST_COMPONENT',
  MY_POST_COMPONENT: 'MY_POST_COMPONENT',
  EXCHANGE_COMPONENT: 'EXCHANGE_COMPONENT',
  PAYPAL_COMPONENT: 'PAYPAL_COMPONENT',
  FAVOURITE_TOPIC_COMPONENT: 'FAVOURITE_TOPIC_COMPONENT',
  SETTINGS_COMPONENT: 'SETTINGS_COMPONENT',
  HISTORY_COMPONENT: 'HISTORY_COMPONENT',
  MESSAGE_COMPONENT: 'MESSAGE_COMPONENT',
  DETAIL_MESSAGE_COMPONENT: 'DETAIL_MESSAGE_COMPONENT'
};

//URL & APIs
export const BASE_URL = 'https://hitek.com.vn:6002/api/v1/';
export const SOCKET_URL = 'http://hitek.com.vn:6050'; //Non SSL
export const PRODUCT_API = 'product';
export const POST_API = 'post';
export const AUTH_API = 'auth';
export const STORE_API = 'store';
export const GROUP_API = 'group';
export const GROUP_REQUEST_API = 'group_request';
export const GROUP_MEMBER = 'group_member';
export const NOTIFICATION_API = 'notification';
export const CONVERSATION_API = 'conversation';
export const MESSAGE_API = 'message';
export const USER_SETTING_API = 'user_setting';
export const FAVORITE_PRODUCT_API = 'favorite_product';
export const USER_API = 'user';
export const FOLLOW_API = 'following';
export const BILL_API = 'bill';
export const STATUS_API = 'export_request';
export const MEDIA_API = 'media';
export const GROUP_NOT_API = 'get_user_not_in_group';
export const REPORT_API = 'report';
export const ORGANIZATION_API = 'organization';
export const STATISTIC_API = 'statistic';
export const RATE_API = 'rate';
export const BLOCK_API = 'block';

export const GLOBAL_AREA = 'global_area';
export const GLOBAL_CATEGORY = 'global_category';
export const TEMP_TOKEN =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhT2J0YWluZWQiOnsidXNlcm5hbWUiOiJ0YWlraG9hbiIsInBhc3NXb3JkIjoiYzAzMDQzN2Y2ZThlOTRkMjQ0YmM2MDI2MDZkZjUyMzUiLCJpZCI6ImEyMzlhNTUwLTVjYWItMTFlOC05MTlkLTExMGNhNzI4ZTI4NiIsImZ1bGxuYW1lIjoiQ-G6rXAgbmjhuq10IiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwL2FwaS92MS91c2VyL2ltYWdlL2F2YXRhci0xNTI2ODc3OTkwMTc5LnBuZyIsInNleCI6Ik90aGVyIiwiYmlydGhkYXkiOiIyMDE4LTA1LTIxVDA0OjAxOjIxLjg2MVoiLCJwaG9uZSI6IigrODQpOTA2NjYxNzgxIiwiYWRkcmVzcyI6IlQuw5QuSSIsImxvbmdpdHVkZSI6bnVsbCwibGF0aXR1ZGUiOm51bGwsInVzZXJfdHlwZSI6Ik5vcm1hbCIsImVtYWlsIjoiQ-G6rXAgbmjhuq10IiwiYW1vdW50X29mX2xpa2UiOjAsImFtb3VudF9vZl9jb21tZW50IjowLCJhbW91bnRfb2Zfb3JkZXIiOjAsImFtb3VudF9vZl9wdXJjaGFzZSI6MCwic3RhdHVzIjp0cnVlLCJjcmVhdGVkX2F0IjoiMjAxOC0wNS0yMVQwNDowMTowNi4zMDBaIiwidXBkYXRlZF9hdCI6IjIwMTgtMDUtMjFUMDQ6NDY6MTIuMDAxWiJ9LCJpYXQiOjE1MjY4NzgxMDEsImV4cCI6MTUzMjA2MjEwMX0.UQMh1lxo5RzWQ4VzYdU2EVB17WbclJKhUSAjxjOXwEk';

//Redux constants

//POST FOR USER
export const LIST_POST_FOR_USER = 'LIST_POST_FOR_USER';
export const LOAD_MORE_POST_FOR_USER = 'LOAD_MORE_POST_FOR_USER';
export const DELETE_POST_FOR_USER = 'DELETE_POST_FOR_USER';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const UPDATE_CURRENT_USER_IMAGE = 'UPDATE_CURRENT_USER_IMAGE';
//POST ALL USER
export const LIST_POST_ALL = 'LIST_POST_ALL';
export const LOAD_MORE_POST_ALL = 'LOAD_MORE_POST_ALL';
export const DELETE_POST_ALL = 'DELETE_POST_ALL';

export const UPDATE_LIST_PRODUCTS = 'UPDATE_LIST_PRODUCTS';
export const UPDATE_LIST_POSTS = 'UPDATE_LIST_POSTS';
export const REFRESH_LIST_POSTS = 'REFRESH_LIST_POSTS';
export const ADD_ITEM_IN_START_POSITION_LIST_POSTS =
  'ADD_ITEM_IN_START_POSITION_LIST_POSTS';
export const UPDATE_LIST_POST_AFTER_USER_CREATE_POST =
  'UPDATE_LIST_POST_AFTER_USER_CREATE_POST';
export const ADD_ITEM_IN_START_POSITION_LIST_USER_POSTS =
  'ADD_ITEM_IN_START_POSITION_LIST_USER_POSTS';
export const RESET_LIST_PRODUCTS = 'RESET_LIST_PRODUCTS';
export const RESET_LIST_PRODUCTS_ON_MAP = 'RESET_LIST_PRODUCTS_ON_MAP';
export const OUTOFDATA_LIST_PRODUCTS = 'OUTOFDATA_LIST_PRODUCTS';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_NEARBY_DRIVERS = 'GET_NEARBY_DRIVERS';
export const UPDATE_CURRENT_USER_DATA = 'UPDATE_CURRENT_USER_DATA';
export const UPDATE_CURRENT_TOKEN = 'UPDATE_CURRENT_TOKEN';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const UPDATE_LIST_RECOMMENDED_PARTNERS =
  'UPDATE_LIST_RECOMMENDED_PARTNERS';
export const UPDATE_USER_TYPE = 'UPDATE_USER_TYPE';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const UPDATE_LIST_FRIEND = 'UPDATE_LIST_FRIEND';
export const UPDATE_LIST_SUGGEST_FRIEND = 'UPDATE_LIST_SUGGEST_FRIEND';
export const REPLACE_LIST_SUGGEST_FRIEND = 'REPLACE_LIST_SUGGEST_FRIEND';
export const UPDATE_LIST_SEARCH_FRIEND = 'UPDATE_LIST_SEARCH_FRIEND';
export const OUT_OF_DATA_LIST_SUGGEST_FRIEND =
  'OUT_OF_DATA_LIST_SUGGEST_FRIEND';
export const REFRESH_LIST_SUGGEST_FRIEND = 'REFRESH_LIST_SUGGEST_FRIEND';
export const CHANGE_ALWAYS_ACCEPT_INSTANT_PRODUCT =
  'CHANGE_ALWAYS_ACCEPT_INSTANT_PRODUCT';
export const UPDATE_LIST_FOLLOWINGS = 'UPDATE_LIST_FOLLOWINGS';
export const REMOVE_POST = 'REMOVE_POST';
export const UPDATE_POST_LIKE_AMOUNT = 'UPDATE_POST_LIKE_AMOUNT';
export const ADD_ITEM_IN_START_POSITION_LIST_REVIEW_PRODUCT =
  'ADD_ITEM_IN_START_POSITION_LIST_REVIEW_PRODUCT';
export const UPDATE_LIST_NOTIFICATION = 'UPDATE_LIST_NOTIFICATION';
export const REFRESH_LIST_NOTIFICATION = 'REFRESH_LIST_NOTIFICATION';
export const UPDATE_LIST_CONVERSATION = 'UPDATE_LIST_CONVERSATION';
export const UPDATE_LAST_MESSAGE_OF_A_CONVERSATION =
  'UPDATE_LAST_MESSAGE_OF_A_CONVERSATION';
export const REMOVE_A_CONVERSATION = 'REMOVE_A_CONVERSATION';
export const ADD_A_CONVERSATION = 'ADD_A_CONVERSATION';
export const UPDATE_CONVERSATION_CONNECTION_STATE =
  'UPDATE_CONVERSATION_CONNECTION_STATE';
export const CLEAR_CONNECTION_STATE = 'CLEAR_CONNECTION_STATE';
export const REFRESH_LIST_CONVERSATION = 'REFRESH_LIST_CONVERSATION';
export const UPDTAE_LIST_SAVED_IMAGE = 'UPDTAE_LIST_SAVED_IMAGE';
export const UPDTAE_LIST_EMOJI = 'UPDTAE_LIST_EMOJI';
export const UPDATE_LIST_MEDIA = 'UPDATE_LIST_MEDIA';
export const REFRESH_LIST_MEDIA = 'REFRESH_LIST_MEDIA';

//Redux constants for filter
export const UPDATE_LIST_AREAS = 'UPDATE_LIST_AREAS';
export const LOAD_AREA_FILTER = 'LOAD_AREA_FILTER';
export const LOAD_AREA_FOR_NEW_PRODUCT_DETAIL =
  'LOAD_AREA_FOR_NEW_PRODUCT_DETAIL';
export const UPDATE_CURRENT_AREA_FILTER = 'UPDATE_CURRENT_AREA_FILTER';
export const UPDATE_AREA_FOR_NEW_PRODUCT_DETAIL =
  'UPDATE_AREA_FOR_NEW_PRODUCT_DETAIL';
export const UPDATE_LIST_CATEGORY_FILTER = 'UPDATE_LIST_CATEGORY_FILTER';
export const UPDATE_CATEGORY_FILTER = 'UPDATE_CATEGORY_FILTER';
export const UPDATE_TRADE_TYPE_FILTER = 'UPDATE_TRADE_TYPE_FILTER';
export const UPDATE_NEW_TRADE_TYPE_FILTER_FOR_MAP =
  'UPDATE_NEW_TRADE_TYPE_FILTER_FOR_MAP';
export const UPDATE_TRADE_TYPE_FILTER_FOR_MAP =
  'UPDATE_TRADE_TYPE_FILTER_FOR_MAP';
export const UPDATE_RADIUS_FILTER = 'UPDATE_RADIUS_FILTER';
export const UPDATE_NEW_RADIUS_FILTER = 'UPDATE_NEW_RADIUS_FILTER';
export const UPDATE_FILTER_BY_RADIUS = 'UPDATE_FILTER_BY_RADIUS';
export const UPDATE_FILTER_BY_RADIUS_NEW = 'UPDATE_FILTER_BY_RADIUS_NEW';
export const UPDATE_ORDER_FILTER = 'UPDATE_ORDER_FILTER';
export const UPDATE_CATEGORY_FILTER_FOR_MAP = 'UPDATE_CATEGORY_FILTER_FOR_MAP';
export const UPDATE_NEW_CATEGORY_FILTER_FOR_MAP =
  'UPDATE_NEW_CATEGORY_FILTER_FOR_MAP';

export const LIST_PRODUCT_FOR_USER = 'LIST_PRODUCT_FOR_USER';
export const LOAD_LIST_GLOBAL_AREA_FILTER = 'LOAD_LIST_GLOBAL_AREA_FILTER';
export const UPDATE_GLOBAL_AREA_FILTER = 'UPDATE_GLOBAL_AREA_FILTER';
export const LOAD_LIST_GLOBAL_CATEGORY_FILTER =
  'LOAD_LIST_GLOBAL_CATEGORY_FILTER';
export const UPDATE_GLOBAL_CATEGORY_FILTER = 'UPDATE_GLOBAL_CATEGORY_FILTER';
export const UPDATE_DETAIL_NEW_POST = 'UPDATE_DETAIL_NEW_POST';
export const UPDATE_DETAIL_NEW_PRODUCT = 'UPDATE_DETAIL_NEW_PRODUCT';
export const LOAD_LIST_FAVOURITE_PRODUCTS_FOR_USER =
  'LOAD_LIST_FAVOURITE_PRODUCTS_FOR_USER';
export const LOAD_LIST_FAVOURITE_POST_FOR_USER =
  'LOAD_LIST_FAVOURITE_POST_FOR_USER';
export const LOAD_STORE_INFORMATION_FOR_USER =
  'LOAD_STORE_INFORMATION_FOR_USER';
export const SHORTEN_LIST = 'SHORTEN_LIST';
export const LOAD_STORE_MEMBER = 'LOAD_STORE_MEMBER';
export const UPDATE_LIST_FAVOURITE_PRODUCT = 'UPDATE_LIST_FAVOURITE_PRODUCT';
export const LOAD_TRANSACTION_LIST = 'LOAD_TRANSACTION_LIST';
export const LOAD_TRANSACTION_LIST_SELL = 'LOAD_TRANSACTION_LIST_SELL';
export const LOAD_TRANSACTION_LIST_BUY = 'LOAD_TRANSACTION_LIST_BUY';
export const LOAD_MORE_TRANSACTION_LIST_SELL =
  'LOAD_MORE_TRANSACTION_LIST_SELL';
export const LOAD_MORE_TRANSACTION_LIST_BUY = 'LOAD_MORE_TRANSACTION_LIST_BUY';
export const OUT_OF_DATA_TRANSACTION_LIST_SELL =
  'OUT_OF_DATA_TRANSACTION_LIST_SELL';
export const OUT_OF_DATA_TRANSACTION_LIST_BUY =
  'OUT_OF_DATA_TRANSACTION_LIST_BUY';
export const UPDATE_TRANSACTION_LIST_SELL = 'UPDATE_TRANSACTION_LIST_SELL';
export const UPDATE_TRANSACTION_LIST_BUY = 'UPDATE_TRANSACTION_LIST_BUY';
export const LOAD_WALLET_INFO = 'LOAD_WALLET_INFO';
export const LOAD_DRAW_MONEY = 'LOAD_DRAW_MONEY';
export const LOAD_IMPORT_WALLET = 'LOAD_IMPORT_WALLET';
export const LOAD_EXPORT_WALLET = 'LOAD_EXPORT_WALLET';
export const UPDATE_LIST_LIKE_CMT = 'UPDATE_LIST_LIKE_CMT';
export const CLEAR_DATA = 'CLEAR_DATA';
export const UPDATE_LIST_FAVOURITE_PRODUCT_PAGES =
  'UPDATE_LIST_FAVOURITE_PRODUCT_PAGES';
export const OUT_OF_DATA_LIST_FAVOURITE_PRODUCT_PAGES =
  'OUT_OF_DATA_LIST_FAVOURITE_PRODUCT_PAGES';
export const REFRESH_LIST_FAVOURITE_PRODUCT = 'REFRESH_LIST_FAVOURITE_PRODUCT';
export const UPDATE_LIST_FAVOURITE_POST_PAGES =
  'UPDATE_LIST_FAVOURITE_POST_PAGES';
export const OUT_OF_DATA_LIST_FAVOURITE_POST_PAGES =
  'OUT_OF_DATA_LIST_FAVOURITE_POST_PAGES';
export const REFRESH_LIST_FAVOURITE_POST = 'REFRESH_LIST_FAVOURITE_POST';

export const UPDATE_GENDER_FILTER = 'UPDATE_GENDER_FILTER';
export const UPDATE_LIST_PARTNERS = 'UPDATE_LIST_PARTNERS';
export const ADD_TO_LIST_PARTNERS = 'ADD_TO_LIST_PARTNERS';
export const REMOVE_ITEM_LIST_PARTNERS = 'REMOVE_ITEM_LIST_PARTNERS';

export const UPDATE_LIST_RATING = 'UPDATE_LIST_RATING';
export const REMOVE_ITEM_LIST_RATING = 'REMOVE_ITEM_LIST_RATING';

export const UPDATE_LIST_BLOCKED = 'UPDATE_LIST_BLOCKED';
export const RESET_LIST_BLOCKED = 'RESET_LIST_BLOCKED';
export const REMOVE_ITEM_LIST_BLOCKED = 'REMOVE_ITEM_LIST_BLOCKED';
export const ADD_ITEM_LIST_BLOCKED = 'ADD_ITEM_LIST_BLOCKED';

//Others
export const VIETNAM_MOBILE_PHONE_PREFIX = '+84';
export const FACEBOOK_PERMISSION = ['public_profile', 'email'];
export const PASSWORD_FOR_USER_LOGIN_WITH_FACEBOOK = 'AHIHI123456';
export const USER_TYPE_NORMAL = 'NORMAL';
export const USER_TYPE_SILVER = 'SILVER';
export const USER_TYPE_GOLD = 'GOLD';
export const USER_TYPE_DIAMOND = 'DIAMOND';

//GROUP:
export const LOAD_OTHER_GROUP_LIST = 'LOAD_OTHER_GROUP_LIST';
export const LOAD_MY_GROUP_LIST = 'LOAD_MY_GROUP_LIST';
export const UPDATE_MY_GROUP_LIST = 'UPDATE_MY_GROUP_LIST';
export const UPDATE_OTHER_GROUP_LIST = 'UPDATE_OTHER_GROUP_LIST';
export const OUT_OF_DATA_OTHER_GROUPS = 'OUT_OF_DATA_OTHER_GROUPS';
export const OUT_OF_DATA_MY_GROUPS = 'OUT_OF_DATA_MY_GROUPS';
export const RESET_DATA_OTHER_GROUPS = 'RESET_DATA_OTHER_GROUPS';
export const RESET_DATA_MY_GROUPS = 'RESET_DATA_MY_GROUPS';
export const UPDATE_GROUP_INFO = 'UPDATE_GROUP_INFO';
export const UPDATE_LIST_SEARCH_GROUP = 'UPDATE_LIST_SEARCH_GROUP';
export const LOAD_SEARCH_GROUP = 'LOAD_SEARCH_GROUP';
export const OUT_OF_DATA_SEARCH_GROUP = 'OUT_OF_DATA_SEARCH_GROUP';
export const LOAD_LIST_REQUEST_JOIN_GROUP = 'LOAD_LIST_REQUEST_JOIN_GROUP';
export const UPDATE_LIST_MEMBER = 'UPDATE_LIST_MEMBER';
export const OUT_OF_DATA_LIST_MEMBER = 'OUT_OF_DATA_LIST_MEMBER';
export const RESET_DATA_LIST_MEMBER = 'RESET_DATA_LIST_MEMBER';
export const LOAD_LIST_MEMBER = 'LOAD_LIST_MEMBER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_LIST_MEMBERS_REQUEST = 'UPDATE_LIST_MEMBERS_REQUEST';
export const UPDATE_LIST_SUGGEST_MEMBER = 'UPDATE_LIST_SUGGEST_MEMBER';
export const OUT_OF_DATA_LIST_SUGGEST_MEMBER =
  'OUT_OF_DATA_LIST_SUGGEST_MEMBER';
export const REFRESH_LIST_SUGGEST_MEMBER = 'REFRESH_LIST_SUGGEST_MEMBER';
//organization:
export const REFRESH_LIST_ORGANIZATION = 'REFRESH_LIST_ORGANIZATION';
export const LOAD_MORE_LIST_ORGANIZATION = 'LOAD_MORE_LIST_ORGANIZATION';
export const OUT_OF_DATA_LIST_ORGANIZATION = 'OUT_OF_DATA_LIST_ORGANIZATION';
export const UPDATE_ORGANIZATION_INFO = 'UPDATE_ORGANIZATION_INFO';
export const REFRESH_LIST_GROUP_OF_ORGANIZATION =
  'REFRESH_LIST_GROUP_OF_ORGANIZATION';
export const LOAD_MORE_LIST_GROUP_OF_ORGANIZATION =
  'LOAD_MORE_LIST_GROUP_OF_ORGANIZATION';
export const OUT_OF_DATA_LIST_GROUP_OF_ORGANIZATION =
  'OUT_OF_DATA_LIST_GROUP_OF_ORGANIZATION';
export const UPDATE_ORGANIZATION_DASHBOARD = 'UPDATE_ORGANIZATION_DASHBOARD';
//trade_type_list
export const tradeTypeList = [
  {
    id: 1,
    key: 'SELL',
    name: strings.sell
  },
  {
    id: 2,
    key: 'BUY',
    name: strings.buy
  }
];

//is_from_store_list_data
export const isFromStoreListData = [
  {
    id: 0,
    key: false,
    name: strings.personal
  },
  {
    id: 1,
    key: true,
    name: strings.store
  }
];
