import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    confirm: 'Confirm',
    current_heart: 'Current heart',
    id: 'ID',
    top_up: 'TOP UP',
    email_address: 'Email Address',
    password: 'Password',
    confirm_password: 'Comfirm password',
    next: 'NEXT',
    signin: 'SIGN IN',
    already_have_account: 'Already have an account?',
    email_signup: 'SIGN UP WITH EMAIL',
    favourite: 'Favourite',
    video_chat: 'Video chat',
    quick_match: 'Quick match',
    rating: 'Rating',
    posting: 'Posting',
    more: 'More',
    terms_of_services: 'Terms of services',
    privacy_statement: 'Privacy Statement',
    locations_based: 'Locations-Based Services Terms and Conditions',
    store: 'Store',
    video_chat_noti: 'Video chat connection is in progress. Please wait',
    connecting: 'Connecting',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    recently_visited: 'Recently visited',
    new_user: 'New user',
    age: 'Age',
    partner_detail: 'Partner detail',
    send: 'Send',
    send_message: 'Send message',
    type_your_message_here: 'Type your message here',
    quick_match_today_recommended: "Today's Recommended Members",
    quick_match_find_match: 'Find your perfect match',
    quick_match_refresh_member: 'Refresh members ♥',
    nearby: 'Nearby',
    nearby_detail: 'Nearby people around you',
    recently_visited_detail: 'Recently visited extra info',
    top_10_rating: 'Top 10 rating',
    top_10_rating_detail: 'Top 10 rating extra info',
    recently_visited_foreigners: 'Recently visited foreigners',
    recently_visited_foreigner_members: 'Recently visited foreigner members',
    recently_visited_foreigner_members_detail:
      'Recently visited foreigner members extra info',
    confirm_rating: 'Confirm rating',
    rating_complete: 'Rating complete',
    rating_fail: 'Rating fail, please try again later!',
    posting_description:
      '※ The service will be suspended for prostitution, sexual act , and Advertising other Apps',
    post_now: 'Post now',
    see_my_posting: 'See my posting',
    see_all_posting: 'See all posting',
    create_post_description:
      'Abstainable phrases or commercial ads may be deleted and may. If there is a violation, it may be restricted.Please do not upload inappropriate photos for a healthy chat culture.wish.',
    noti_title_load_from_server: 'Noti title load from server',
    noti_content_load_from_server: 'Noti content load from server',
    settings: 'Settings',
    attendance_check: 'Attendance Check',
    blocked_friends: 'Blocked friends',
    terms_conditions: 'Terms & Conditions',
    version: 'Version: ',
    exchange: 'Exchange',
    edit_profile: 'Edit profile',
    cash: 'Cash',
    won: 'Won',
    bank: 'Bank',
    account_no: 'Account no.',
    account_holder: 'Account holder',
    id_number: 'ID number',
    request: 'Request',
    noti_content_exchange:
      'Depending on your country, you may request materials for income reporting\nThe refund will be processed within 48 hours after application.\nIf the payment information is incorrect, the refund will be canceled.\nApplied cache will be returned.4. Applying for a refund of the cache obtained in an improper way\nThe refund can be held and you can ask for confirmation.\nIf you have any additional questions or Please contact QnA.',
    paypal: 'Paypal',
    name: 'Name',
    paypal_id: 'Paypal ID',
    refund_application: 'Refund application',
    set_picture_profile: 'Set picture profile',
    profile: 'Profile',
    edit_image_profile_description:
      '※ The registered photos will be applied after the inspection.\nPlease wait a moment ~',
    edit_nickname: 'Edit nickname',
    nickname: 'Nickname',
    edit_nickname_description: '※ Nickname can be used up to 2 ~ 10 letters.',
    edit_self_introduction: 'Edit self introduction',
    self_introduction: 'About me',
    edit_self_introduction_description:
      'Self introduction can use up to 20 letters.',
    edit_address: 'Edit Address',
    address: 'Address',
    edit_address_description: 'Address can use up to 20 letters.',
    favourite_description: 'Please select 3 interests of yours at maximum',
    edit_age_description: 'Please use real age',
    edit_age: 'Edit age',
    notification: 'Notification',
    notification_sound: 'Notification sound',
    vibration_alert: 'Vibration alert',
    incomming_video_call_alert: 'Incomming video call alert',
    push_notification: 'Push notification',
    transactions: 'Transactions',
    heart_history: 'Heart history',
    cash_history: 'Cash history',
    delete_account: 'Delete account',
    hearts: 'hearts',
    current_cash: 'Current cash',
    date: 'Date',
    history: 'History',
    delete_account_confirm: 'Are you sure to delete your account?',
    delete_account_description:
      "You can't sign up again 30 days if you delete account",
    attendance_check_description:
      'One day attendance every day!Scratches just pop up ~',
    attendance_check_complete: 'Attendance Check completed',
    attendance_already_checked: "You've already checked in today",
    message: 'Message',
    message_list: 'Message list',
    close_friend: 'Close friend',
    interest: 'Interest',
    delete: 'Delete',
    dismiss_interest: 'Dismiss interest',
    message_menu: 'Message menu',
    read_all: 'Read all',
    delete_all: 'Delete all',
    delete_all_messages: 'Delete all messages',
    delete_all_messages_confirm: 'Do you want to delete all messages?',
    delete_all_messages_description:
      '※ Only the checked items in the list will be deleted.',
    delete_conversation_title: 'Do you want to delete this chat history?',
    delete_conversation_content: 'All conversation will be deleted',
    delete_conversation_fail: 'Delete conversation fail, try again later!',
    gift: 'Gift',
    purchase: 'Purchase',

    unblock_fail: 'Unblock fail, please try again later',
    block_fail: 'Block fail, please try again later',
    report_success: 'Report success',
    report_fail: 'Report fail, please try again later',
    send_gift_success: 'Send gift success',
    send_gift_fail: 'Send gift fail, please try again later',
    send_message_fail: 'Send message fail, please try again later',
    create_post_fail: 'Create post fail, please try again later',

    at: 'at',
    with: 'with',
    chat_with: 'Chat',
    chat: 'Chat',
    you: 'You',
    verified_store: 'Verified store',
    has_sent_an_image: 'Has sent an image',
    has_sent_a_url: 'Has sent a url',
    has_sent_an_emotion: 'Has sent an emotion',
    export_from_wallet: 'Withdraw',
    import_to_wallet: 'Deposit',
    upgrade_account: 'Upgrade account',
    description: 'Description',
    posting_date: 'Date',
    contact: 'Contact',
    your_withdraw_request_completed_notification:
      'Sent withdrawing request successfully',
    withdraw_successfully: 'We will process your request within 24 hours',
    minimum_is_500000: 'Min is 50.000đ',
    minimum_is_deposit_500000: 'Min deposit is 50.000đ',
    please_input_all_info: 'Please input all information',
    save_bank_account_info: 'Save bank account information',
    instant_product_mode: 'Instant product mode',
    request_withdraw: 'Withdrawing request',
    bank_name: 'Bank name',
    please_choose_bank_name: 'Please choose bank name',
    branch: 'Branch',
    please_choose_branch: 'Please choose branch',
    bank_account_name: 'Bank account name',
    bank_account_serial: 'Bank account code',
    bank_area: 'Area',
    withdraw_amount: 'Amount',
    standard_plan_title: 'Standard plan',
    silver_plan_title: 'Silver plan',
    gold_plan_title: 'Gold plan',
    customers: 'Customers',
    diamond_plan_title: 'Diamond plan',
    standard_plan_description: '- Posting valid time is up to 7 days',
    silver_plan_description:
      '- Posting valid time is up to 30 days\n- Store supported',
    gold_plan_description:
      '- Posting valid time is up to 1 year\n- Store supported\n- Premium icon',
    diamond_plan_description:
      '- Posting valid time is unlimited\n- Store supported\n- Premium icon',
    this_feature_is_in_development: 'This feature is being developed...',
    please_input_all_information: 'Please input all information',
    terms_of_use: 'The terms of use',
    application_connectivity_needs:
      'of T.O.I - application connectivity needs.',
    app_name: 'T.O.I',
    login: 'Login',
    login_with_facebook: 'Login with Facebook',
    username: 'Username',
    forget_password: 'Forget password? ',
    or: 'Or',
    i_want_to_register: "Don't have an account ? ",
    delete_post_alert: 'Are you sure you want to delete this post?',
    please_login: 'Please login to use this feature',
    login_now: 'Login now',
    register: 'Register ',
    retype_password: 'Retype your password',
    please_upgrade_to_premium:
      'Please upgrade your account to premium to use this feature',
    upgrade_now: 'Upgrade now',
    favourite_news: 'Favourites',
    perfect_match_no_data:
      'No perfect data found for you, please try again later',
    alert: 'Message',
    cannot_comment_because_of_sensitive_word:
      'Cannot comment because there is a sensitive word',
    login_fail: 'Login failed',
    login_success: 'Login successfully',
    register_success: 'Register success',
    change_password_success: 'Change password success',
    network_require_fail: 'Please check your internet connection',
    success: 'Success',
    time: 'Time',
    state: 'State',
    report: 'Report',
    report_confirm:
      'If a false report is made, the claimant may be subject to have panelty',
    advertising: 'Advertising',
    abuse: 'Abuse',
    threat: 'Threat',
    fraud: 'Fraud',
    sexual_act: 'Sexual act',
    etc: 'etc',
    insert_report: 'Please enter a report',
    send_report: 'SEND REPORT',
    success_report: 'Thank you for reporting',
    false_report: 'Send failure report',
    //adddiary component:
    add_product_screen_name: 'ADD PRODUCT',
    location: 'Location',
    open_location:
      'Please open the location want to use and send instant message',
    with_friends: 'With friends',
    post: 'POST',
    created_post: 'Create a post',
    //choosecategory component:
    category_post: 'Post category',
    please_choose_category: 'Please choose a category for your post',
    category_screen_name: 'Category Post',
    //chooseimagepost component:
    choose_image_post_screen_name: 'Choose Images Post',
    please_choose_atleast_3_images: 'Please choose at least 3 images',
    need_atleast_3_images_to_post: 'Need at least 3 images to post.',
    please_choose_atleast_1_image: 'Please choose at least 1 image',
    need_atleast_1_image1_to_post: 'Need at least 1 image to post.',
    need_atleast_1_image_to_post: 'Need at least 1 image to post.',
    choose_images: 'CHOOSE IMAGES',
    done: 'Done',
    deny: 'Deny',
    //chooserolepost component:
    role_post_screen_name: 'Role',
    you_are: 'You are',
    personal: 'Personal',
    pending: 'Processing',
    //creategroup component:
    create_group_screen_name: 'Create group',
    add: 'Add',
    added: 'Added',
    choose_friend_to_join: 'Choose friends to join',
    status_online: 'Online',
    status_offline: 'Offline',
    status_idle: 'Idle',
    insert_group_name: 'Group name',
    //draggablebutton component:
    want_to_sell: 'Want to sell',
    want_to_buy: 'Want to buy',
    filters: 'Filters',
    //editprofile component:
    sex_male: 'Male',
    sex_female: 'Female',
    sex_other: 'Other',
    profile_product: 'Product',
    diary: 'Posts',
    profile_name: 'Name ...',
    profile_birthday: 'Birthday',
    profile_phone: 'Phone ...',
    profile_email: 'Email ...',
    profile_place: 'Place ...',
    profile_description: 'Store information ...',
    button_edit: 'Edit',
    update_info: 'Update Infomation',
    update_info_success: 'Updated successfully',
    update_info_failed: 'Update failed, please check your input',
    failed: 'Failed',
    log_out: 'Log out',
    alert_edit_info_fail: 'Update info failed',
    //favourite component:
    favourite_product: 'Product',
    favourite_post: 'Post',
    //findgroup component:
    find_group_screen_name: 'Find group',
    your_group: 'Your group',
    suggested_group: 'Suggested groups',
    public_group: 'Public groups',
    //forgotpass component:
    get_back_password: 'Get password',
    insert_phone_number: 'Phone number',
    //friend component:
    invite_friend: 'Invite',
    suggest_friend: 'Suggest',
    list_friend: 'Friends',
    //FunctionsOther component:
    my_favourite_post: 'My favorite posts',
    my_transaction_history: 'My transaction history',
    my_transaction_method: 'My transaction method',
    my_wallet: 'My wallet',
    my_group: 'My group',
    my_private_setting: 'Private setting',
    other_function: 'Other functions',
    //listproducts component:
    sell: 'Sell',
    buy: 'Buy',
    all: 'All',
    has_not_chosen_category: 'All category',
    has_not_chosen_area: 'All area',
    product_list_screen_name: 'T.O.I',
    //productmartker component:
    verified: 'Verified',
    details: 'Details',
    //listproductsonmap component:
    list_product_map_screen_name: 'T.O.I',
    my_position: 'My position',

    //Main component:
    close_app_title: 'Close app',
    close_app_content: 'Are you sure you want to close this app?',
    login_app_title: 'Not logged in?',
    need_sell: 'Need sell',
    need_buy: 'Need buy',
    back: 'Back',
    close: 'Close',
    //MyProductDetailComponent:
    cancel_post: 'Cancel post',
    edit_post: 'Edit post',
    buy_now: 'Buy now',
    buy_success: 'Buy success.',
    //newfeedscomponent:
    newfeeds_screen_name: 'Newfeeds',
    //listnotification component:
    messages: 'Message',
    call: 'Video call',
    //otherprofile component:
    add_friend: 'Add friend',
    blocked: 'Unblock',
    un_friend: 'Unfriend',
    request_sent: 'Cancel request',
    refuse_request: 'Refuse request',
    accept_request: 'Accept request',
    respond_request: 'Response',
    block: 'Block',
    alreadyBlocked: 'You already blocked',
    follow: 'Follow',
    unfollow: 'Unfollow',
    product_stop_sale:
      'This product was discontinued immediate sale, you will not see the current location of the buyer again',
    product_instant: 'Product instant',
    the_actual_GPS: 'you will see the actual GPS location of the seller',
    //otherstatus component:
    picture: 'Pictures',
    //otherstore component:
    store_information: 'Store information',
    //paymentsuccess component:
    congratulations: 'Congratulations',
    payment_success_notification: 'Your payment is completed',
    payment_failed_notification:
      'Your payment is failed, please check your information and try again',
    payment_with_wallet_confirm:
      'Are you sure you want to payment with wallet?',
    max_limitation_is_100: 'The amount must be below 100 million',
    agree: 'Agree',
    always_agree: 'Always agree',
    invite_member_success: 'Invite member success',
    //paymentmethods component:
    payment_methods_screen_name: 'Payment methods',
    payment_methods: 'Payment methods',
    please_choose_payment_method: 'Please choose a payment method',
    order_new: 'New',
    order_price_low: 'Price low',
    order_price_high: 'Price high',
    pay_using_toi: 'Pay using T.O.I',
    pay_using_COD: 'Pay using COD',
    payment_via_wallet: 'Payment via wallet',
    //payment rule:
    payment_rule_screen_name: 'PAYMENT',
    payment_rule_when_payment:
      'Payment using T.O.I, we guaranteed to become a reputable intermediary to help you reduce risks as much as possible.',
    payment_rule_step_1:
      'Step 1: By clicking "buy now", your money will be temporarily stored in T.O.I\'s wallet.',
    payment_rule_step_2:
      'Step 2: T.O.I will confirm with the seller about your payment, then the seller will send you that product.',
    payment_rule_step_3:
      'Step 3: After confirming that the seller has sent the item, T.O.I will transfer money to the seller.',
    payment_rule_when_conflict:
      'In case of conflict between buyers and sellers, final decisions will be decided by T.O.I.',
    payment_rule_user_read_and_agree: 'I have read and accepted.',
    payment_rule_payment: 'Payment',
    //
    need_to_buy: 'Need to buy',
    need_to_sell: 'Need to sell',
    find_item_radius: 'Find items in a radius of ',
    please_choose_province_city: 'Please select a province / city',
    please_choose_sort: 'Please select the type of sort',
    please_choose_product: 'Please choose product',
    filter: 'Filter results',
    search: 'What are you looking for ? Type here',
    search_group_member: "Please type your friend's name to invite... ",
    search_store_member: "Please type your customer's name...",
    search_group: 'Please type a group name...',
    search_place: 'Please type a place...',
    search_product: 'Please type a product name...',
    search_friend: "Please type your friend's name...",
    cancel: 'Cancel',
    like: 'Like',
    share: 'Share',
    comment: 'Comment',
    delete_product: 'Delete product',
    edit_product: 'Edit product',
    delete_product_alert: 'Your product will be deleted!!',
    delete_product_success: 'Your product was deleted!',
    delete_product_fails: 'Delete product fails!',
    accept: 'Accept',
    //ProductComponent-profileChildProduct
    valid: 'Valid',
    banned: 'Banned',
    outdated: 'Outdated',
    review: 'Review',
    alert_large_time_over_current:
      'Please choose the date of the large time over the current date',
    alert_orange_icon_on_the_map:
      'Your postings will be orange icon on the map view, and everyone will see your current location',
    //PopupMenuAreaFilter component:
    popup_menu_area_screen_name: 'Select area',
    select_area_filter: 'Select area',
    please_select_area_filter: 'Please select which area you want to find',
    //PopupMenuCategoryFilter COmporent:
    popup_menu_category_filter_screen_name: 'Select product',
    select_product_filter: 'Select product',
    please_select_product_filter:
      'Please select which product you want to find',
    //PopupMenuOrderFilter component:
    popup_menu_order_filter_screen_name: 'Select order',
    select_order_filter: 'Select order',
    please_select_order_filter: 'Please select which order you want to find',
    //UpdatePremium component:
    update_premium_screen_name: 'Upgrade to Premium',
    view_current_premium_benefits: 'Benefits for current Premium',
    premium_packages: 'Other Premium packages',
    normal_user: 'Normal User',
    silver_user: 'Silver User',
    gold_user: 'Gold User',
    diamond_user: 'Diamond User',
    //previewbeforepost component:
    prices_cannot_be_blank: 'Price cannot be blank!',
    prices_must_be_number: 'Price must be number!',
    prices_cannot_be_negative: 'Price can not be negative or zero!',
    prices_limitation_is_100_billion: 'Price limitation is 100 billion VND',
    prices_limitation_is_1000: 'Price limitation is 1000 VND',
    name_group_cannot_be_blank: 'Group name cannot be blank!',
    name_group_too_long: 'Group name too long',
    name_cannot_be_blank: 'Name cannot be blank!',
    area_cannot_be_blank: 'Area cannot be blank!',
    address_cannot_be_blank: 'Address cannot be blank!',
    description_cannot_be_blank: 'Description cannot be blank!',
    choose_specific_category: 'Choose specific category',
    choose_specific_area: 'Choose specific area',
    preview_before_post_screen_name: 'Your post',
    preview_before_post_category: 'Category',
    preview_before_post_type: 'Type',
    preview_before_post_fromRole: 'Post Role',
    preview_before_post_area: 'Area',
    insert_address: 'Insert address...',
    preview_before_post_keywords: 'Name',
    insert_keywords: 'Insert name...',
    preview_before_post_price: 'Price',
    insert_price: 'Insert price...',
    preview_before_post_dayvisible: 'Date visible',
    additional_products: 'Additional products',
    days: 'days',
    select_day: 'Select day',
    preview_before_post_description: 'Description',
    insert_description: 'Insert description...',
    //PrivatePermission component:
    private_permission_screen_name: 'Privacy Settings',
    privacy_permission: 'Privacy permission',
    who_can_see_your_future_share_and_manage_data:
      'Who can see your future post and manage data',
    allow_other_people_follow_you: 'Allow other people follow you',
    show_seen_when_chat: 'Show "seen" when chat',
    allow_everyone_comment_on_your_post: 'Allow everyone comment on your post',
    allow_everyone_add_friend_and_search: 'Allow everyone add friend with you',
    //productfordiary component:
    product_for_diary_screen_name: 'Product',
    //logged component:
    my_transaction: 'Bills',
    friends: 'Friends',
    product_logged_component: 'Product',
    post_logged_component: 'Post',
    store_logged_component: 'Store',
    //post component:
    whats_on_your_mind: "What's on your mind?",
    add_to_your_post: 'Add to your post',
    post_detail: 'Post detail',
    //register component:
    already_have_an_account: 'Already have an account?',
    password_must_atleast_6_charactor: 'Password must atleast 6 charactor',
    //Splash component:
    splash_content: 'EVERYTHING YOU NEED',
    splash_details: 'Shopping, shopping online, selling everything online.',
    //successpost component:
    success_post_screen_name: 'Congratulations',
    your_post_completed_notification: 'You have successfully posted',
    see_my_post: 'See my post',
    see_my_request: 'See my request',
    my_post: 'My posting',
    wait_for_admin_to_check_your_post:
      'Your post will be checked by admin in 24 hours.',
    //DetailTransaction component:
    detail_transaction_screen_name: 'Detail Transaction',
    payment: 'Payment',
    receive: 'Receive',
    received: 'Received',
    confirm_received: 'Confirm Received',
    confirm_delivered: 'Confirm Delivered',
    cancelled_transaction: 'Cancelled',
    detail_transaction_status: 'Status',
    detail_transaction_price: 'Price',
    detail_transaction_payment_date: 'Payment date',
    detail_transaction_buyer: 'Buyer',
    detail_transaction_rating: 'Rating',
    insert_what_you_think_about_buyer: 'What you thinks about buyer',
    i_have_received_product: "I've received product",
    confirm_payment_notification_title: 'Are you sure?',
    confirm_payment_notification_content:
      'You can not get your money back once you clicks "Yes".',
    confirm_payment_yes: 'Yes',
    confirm_payment_no: 'Cancel',
    //Historytransaction component:
    history_transaction_screen_name: 'History Transaction',
    //Withdrawtransaction component:
    history_withdraw_screen_name: 'Withdraw Requests',
    //mytransaction component:
    i_sell: 'I sell',
    i_buy: 'I buy',
    //mywallet component:
    my_wallet_screen_name: 'My wallet',
    account_balance: 'My account balance',
    i_want: 'I want to',
    transaction_history: 'Transaction history',
    want_to_top_up: 'Deposit',
    withdraw_money: 'Withdraw',
    insert_amount_of_money: 'Amount of money...',
    top_up_now: 'Deposit now',
    withdraw_money_now: 'Withdraw now',
    others: 'Others',
    withdraw_requests: 'Withdraw requests',
    //myflatlist:
    no_data: 'No data',
    //
    alert_need_to_upgrate: 'Please upgrate to use this feature',
    //listmessage component:
    list_message_screen_name: 'Messages',
    //listproduct item:
    created_date: 'Created date',
    outdated_date: 'Outdated date',
    received_date: 'Received date',
    instant_product: 'Instant product',
    instant: 'Instant',
    normal_product: 'Normal product',
    reviews: 'Reviews',
    //listproductitemfortransaction:
    paid: 'Paid',
    deal_history: 'Deal History',
    save: 'Save',
    noti_for_buyer:
      'You have already paid, within 14 days if you do not receive the goods from the seller, you will be refunded',
    alert_for_buyer:
      'Please confirm "I received the goods" under the button when you receive the goods',
    noti_for_seller:
      'Orders paid, please delivery within 14 days or you will be penalized prestige',
    alert_for_seller:
      'Please remind the purchase order status changes to "ITEMS RECEIVED" when you delivery',
    tag_friend_screen_name: 'Friends',
    by_paying_online_you_agree_to: '* By paying online, you agree to',
    canceled: 'Canceled',
    delivered: 'Delivered',
    delivering: 'Delivering',
    waiting_for_admin: 'Waiting for admin',
    unpaid: 'Unpaid',
    status: 'Status',
    paidDate: 'Paid date',
    buyer: 'Buyer',
    seller: 'Seller',
    sure: 'Are you sure?',
    alert_sure_received:
      'You will not get back money. Make sure you received product',
    review_the_seller: 'Review the seller...',
    review_the_buyer: 'Review the buyer...',
    //pickercomponent:
    sharing_mode: 'Sharing mode',
    //poppupchangepass:
    pop_up_change_pass_screen_name: 'Type your new password',
    new_password: 'New password',
    verified_new_password: 'Retype your new password',
    password_verified_is_not_match:
      'Password does not match the confirm password',
    change_password: 'Change password',
    //paymentComponent
    amount_of_money: 'Amount of money',
    choose_how_to_pay: 'Choose how to pay',
    pay: 'Payment',
    loading: 'Loading...',
    //
    delete_comment_alert: 'Your comment will be deleted!!',
    comment_must_atleast_1_charactor: 'Comment must atleast 1 charactor',
    write_comment: 'Write a comment...',
    //roadmapComponent
    direction: 'Direction',
    //emojiComponent
    download: 'Download',
    //expired component
    outdated_alert_content: 'This product is outdated',
    go_to_product_detail: 'Go to product detail',
    extend_product_duration: 'Extends duration',
    request_upgrade_premium_title: 'Request upgrade',
    request_upgrade_premium_content:
      'You need to upgrade your account to use this function!',
    joined_date: 'Joined date',
    public: 'Public',
    private: 'Private',
    group_member: 'Members',
    delete_request_join_group: 'Cancel request',
    join_group: 'Join group',
    group_post: 'Post',
    leave_group_success: 'You have left this group',
    leave_group_confirm: 'Are you sure you want to leave this group?',
    delete_group_confirm: 'Are you sure you want to delete this group?',
    delete_group_success: 'You have deleted this group',
    yes: 'Yes',
    no: 'No',

    remove_member: 'Remove member',
    block_member: 'Block member',
    make_admin: 'Make admin',
    remove_admin: 'Remove admin',
    view_profile: 'View profile',

    block_member_comfirm: 'You are about to block this user?',
    block_member_noti: '※ This user will be invisible at our app if you block',
    remove_member_comfirm:
      'Are you sure you want to remove this user from this group?',
    make_admin_comfirm: 'You are about to make this user as a group admin?',
    remove_admin_comfirm: 'You are about to remove this user as a group admin?',

    remove_member_success: 'Remove user success',
    block_member_success: 'Block user success',
    make_admin_success: 'Make admin success',
    remove_admin_success: 'Remove admin success',

    admins_and_mods: 'Admins and Moderators',
    members: 'Members',
    request_members: 'Request Members',
    edit_group: 'Edit',
    leave_group: 'Leave group',
    remove_group: 'Remove group',
    million: 'mil',
    billion: 'bil',
    vnpay_screen_name: 'VNPay',
    delete_notification_failed: 'Failed to delete the notification!',
    request_permission: 'You need to enable permission to continue!',
    go_to_device_setting: 'Go to setting',
    turn_on_location_permission:
      'You must allow this app to access your location to continue!',
    maximun_select: 'You must select 3 interests of yours at maximum',
    //Introduction
    you_will_see_product_sell:
      'You will see the current location of the product you are selling. Click to view product information',
    slide_the_bar_spacing_to_find:
      'Slide the bar spacing to find the items in a position farther',
    view_the_products_with_list_mode: 'See product list mode',
    Click_TOI_to_easily_buy_sell:
      'Click T.O.I button to easily buy / sell your items',
    image_picker_title: 'Image Picker',
    take_photo_button_title: 'Take photo',
    choose_from_library_button_title: 'Pick gallery',
    email_must_be_right_format: 'Your email must be right format',
    private_group_cannot_share_post_alert:
      'You cannot share post in private group.',
    product_location: 'Pick a location',
    unfinished: 'Unfinished',
    finished: 'Finished',
    direct_deals: 'Seller only support direct deals',
    content_not_found:
      'The page you requested cannot be displayed. It may be temporarily unavailable or has been removed.',
    content_not_found_screen_name: 'Content not found',
    post_contains_vulnerable_word:
      'Your post has been declined because it contains vulnerable words',
    did_not_answer: 'Did not answer',
    call_is_denied: 'The call is denied',
    camera_is_off: "'s camera is off",
    day: 'Day',
    month: 'Month',
    week: 'Week',
    missed_call: 'You have a new missed call from',
    is_calling_you: 'is calling you...'
  }
});
export default strings;
